# SPDX-License-Identifier: MIT
# Copyright (c) 2019 Gennady Trafimenkov

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make test
